#This is a generic configuration file for the webservice.
#it in turns draws from environment variables.
#It will only be used when there is no host-specific configuration file
#(asr_nl.\$HOSTNAME.yml)
root: "{{CLAM_ROOT=/tmp}}/asr_nl-userdata"
port: "{{CLAM_PORT=8080}}"
use_forwarded_host: "{{CLAM_USE_FORWARDED_HOST=false}}" #(set to true or false, enable this if you run behind a properly configured reverse proxy only)
switchboard_forward_url: "{{CLAM_SWITCHBOARD_FORWARD_URL}}" #e.g. "https://switchboard.clarin.eu/#/asr_nl/$BACKLINK/$MIMETYPE/nld"
debug: "{{CLAM_DEBUG|bool=false}}"
oauth: "{{CLAM_OAUTH|bool=false}}"
oauth_client_id: "{{CLAM_OAUTH_CLIENT_ID}}"
oauth_client_secret: "{{CLAM_OAUTH_CLIENT_SECRET}}"
oauth_client_url: "{{CLAM_OAUTH_CLIENT_URL}}"
oauth_auth_url: "{{CLAM_OAUTH_AUTH_URL}}"
oauth_token_url: "{{CLAM_OAUTH_TOKEN_URL}}"
oauth_userinfo_url: "{{CLAM_OAUTH_USERINFO_URL}}"
oauth_revoke_url: "{{CLAM_OAUTH_REVOKE_URL}}"
oauth_scope: "{{CLAM_OAUTH_SCOPE|json}}"
resourcedirectory: "/opt/Kaldi_NL/"

# HTTP Basic Authentication via a simple TSV file (disabled by default)
users_file: "{{CLAM_USERS_FILE}}"
realm: "{{CLAM_REALM={sys_id}}}"

#Interface customisation
customhtml_index: "{{CLAM_CUSTOMHTML_INDEX}}"
customhtml_projectstart: "{{CLAM_CUSTOMHTML_PROJECTSTART}}"
customhtml_projectdone: "{{CLAM_CUSTOMHTML_PROJECTDONE}}"
customhtml_projectfailed: "{{CLAM_CUSTOMHTML_PROJECTFAILED}}"
customcss: "{{CLAM_CUSTOMCSS}}"
interfaceoptions: "{{CLAM_INTERFACEOPTIONS}}"
